// Extra names for small "other" origins to widen letter/style coverage.
// Tuple format: [name, gender, meaning, origin, style]

export const EXTRA_JAPANESE = [
  ['Aoi', 'boy', 'Hollyhock, blue', 'Japanese', 'Unique'],
  ['Arata', 'boy', 'New, fresh', 'Japanese', 'Modern'],
  ['Daisuke', 'boy', 'Great help', 'Japanese', 'Classic'],
  ['Hayato', 'boy', 'Falcon person', 'Japanese', 'Unique'],
  ['Hikaru', 'boy', 'Radiant light', 'Japanese', 'Unique'],
  ['Hiro', 'boy', 'Generous, abundant', 'Japanese', 'Unique'],
  ['Isamu', 'boy', 'Courage, valour', 'Japanese', 'Unique'],
  ['Kazuki', 'boy', 'Harmony, hope', 'Japanese', 'Unique'],
  ['Ken', 'boy', 'Healthy, strong', 'Japanese', 'Modern'],
  ['Kota', 'boy', 'Happiness, blessing', 'Japanese', 'Unique'],
  ['Makoto', 'boy', 'Sincerity, truth', 'Japanese', 'Classic'],
  ['Minato', 'boy', 'Harbour', 'Japanese', 'Unique'],
  ['Naoki', 'boy', 'Honest tree', 'Japanese', 'Classic'],
  ['Riku', 'boy', 'Land, earth', 'Japanese', 'Unique'],
  ['Ryota', 'boy', 'Refreshing, clear', 'Japanese', 'Unique'],
  ['Sho', 'boy', 'Soar, fly', 'Japanese', 'Unique'],
  ['Sora', 'boy', 'Sky', 'Japanese', 'Modern'],
  ['Takashi', 'boy', 'Noble, prosperous', 'Japanese', 'Classic'],
  ['Takeru', 'boy', 'Brave warrior', 'Japanese', 'Unique'],
  ['Takumi', 'boy', 'Artisan, skilled', 'Japanese', 'Unique'],
  ['Taro', 'boy', 'Great son', 'Japanese', 'Classic'],
  ['Taiga', 'boy', 'Big river', 'Japanese', 'Unique'],
  ['Yuki', 'boy', 'Snow, happiness', 'Japanese', 'Modern'],
  ['Yusuke', 'boy', 'Brave help', 'Japanese', 'Classic'],
  ['Aimi', 'girl', 'Love, beauty', 'Japanese', 'Unique'],
  ['Ayame', 'girl', 'Iris flower', 'Japanese', 'Unique'],
  ['Chiyo', 'girl', 'Thousand generations', 'Japanese', 'Classic'],
  ['Emi', 'girl', 'Blessed beauty', 'Japanese', 'Modern'],
  ['Haruka', 'girl', 'Distant, spring flower', 'Japanese', 'Unique'],
  ['Hina', 'girl', 'Sunlight, light', 'Japanese', 'Modern'],
  ['Hoshi', 'girl', 'Star', 'Japanese', 'Unique'],
  ['Kiko', 'girl', 'Hope, child', 'Japanese', 'Unique'],
  ['Kohana', 'girl', 'Small flower', 'Japanese', 'Unique'],
  ['Mariko', 'girl', 'Truth, child', 'Japanese', 'Classic'],
  ['Mayumi', 'girl', 'True beauty', 'Japanese', 'Classic'],
  ['Michi', 'girl', 'Path, wisdom', 'Japanese', 'Unique'],
  ['Mizuki', 'girl', 'Beautiful moon', 'Japanese', 'Unique'],
  ['Naomi', 'girl', 'Straight, beautiful', 'Japanese', 'Classic'],
  ['Natsuki', 'girl', 'Summer hope', 'Japanese', 'Unique'],
  ['Riko', 'girl', 'Jasmine, child', 'Japanese', 'Modern'],
  ['Rin', 'girl', 'Dignified, companion', 'Japanese', 'Unique'],
  ['Saki', 'girl', 'Blossom, hope', 'Japanese', 'Unique'],
  ['Tomoko', 'girl', 'Wise child', 'Japanese', 'Classic'],
  ['Yumi', 'girl', 'Arrow, beauty', 'Japanese', 'Classic'],
];

export const EXTRA_AFRICAN = [
  ['Amadi', 'boy', 'Seemed destined', 'African', 'Unique'],
  ['Babatunde', 'boy', 'Father has returned', 'African', 'Classic'],
  ['Chiamaka', 'boy', 'God is beautiful', 'African', 'Unique'],
  ['Dada', 'boy', 'Curly haired', 'African', 'Unique'],
  ['Emeka', 'boy', 'God has done great', 'African', 'Unique'],
  ['Femi', 'boy', 'Love me', 'African', 'Unique'],
  ['Kwesi', 'boy', 'Born on Sunday', 'African', 'Classic'],
  ['Mosi', 'boy', 'First born', 'African', 'Unique'],
  ['Nkosana', 'boy', 'Chief', 'African', 'Unique'],
  ['Okonkwo', 'boy', 'Born on the market day', 'African', 'Unique'],
  ['Osei', 'boy', 'Noble, honourable', 'African', 'Unique'],
  ['Sefu', 'boy', 'Sword', 'African', 'Unique'],
  ['Uzoma', 'boy', 'Good way', 'African', 'Unique'],
  ['Zuberi', 'boy', 'Strong, powerful', 'African', 'Unique'],
  ['Abeni', 'girl', 'We asked for her', 'African', 'Unique'],
  ['Adjoa', 'girl', 'Born on Monday', 'African', 'Classic'],
  ['Akosua', 'girl', 'Born on Sunday', 'African', 'Classic'],
  ['Asha', 'girl', 'Life, hope', 'African', 'Unique'],
  ['Ebele', 'girl', 'Mercy, kindness', 'African', 'Unique'],
  ['Ifeoma', 'girl', 'Beautiful thing', 'African', 'Unique'],
  ['Kemi', 'girl', 'Protected, cherished', 'African', 'Unique'],
  ['Lulu', 'girl', 'Precious pearl', 'African', 'Unique'],
  ['Ngozi', 'girl', 'Blessing', 'African', 'Unique'],
  ['Ola', 'girl', 'Wealth, fortune', 'African', 'Unique'],
  ['Safiya', 'girl', 'Pure, faithful', 'African', 'Unique'],
  ['Yara', 'girl', 'Butterfly, beautiful', 'African', 'Unique'],
];

export const EXTRA_HAWAIIAN = [
  ['Ahulani', 'boy', 'Royal messenger', 'Hawaiian', 'Unique'],
  ['Akoni', 'boy', 'Priceless, praiseworthy', 'Hawaiian', 'Unique'],
  ['Alika', 'boy', 'Defender of men', 'Hawaiian', 'Unique'],
  ['Analu', 'boy', 'From heaven', 'Hawaiian', 'Unique'],
  ['Hoku', 'boy', 'Star', 'Hawaiian', 'Unique'],
  ['Ikaia', 'boy', 'Strong', 'Hawaiian', 'Unique'],
  ['Kahanu', 'boy', 'The mist', 'Hawaiian', 'Unique'],
  ['Kaleo', 'boy', 'Voice, sound', 'Hawaiian', 'Unique'],
  ['Kamuela', 'boy', 'He who is of God', 'Hawaiian', 'Unique'],
  ['Kane', 'boy', 'Man, god of creation', 'Hawaiian', 'Classic'],
  ['Kanoa', 'boy', 'The free one', 'Hawaiian', 'Unique'],
  ['Keahi', 'boy', 'The fire', 'Hawaiian', 'Unique'],
  ['Kealoha', 'boy', 'The beloved', 'Hawaiian', 'Unique'],
  ['Keanu', 'boy', 'Cool breeze over the mountains', 'Hawaiian', 'Unique'],
  ['Kilikina', 'boy', 'Follower of Christ', 'Hawaiian', 'Unique'],
  ['Lanakila', 'boy', 'Victory', 'Hawaiian', 'Unique'],
  ['Lokelani', 'boy', 'Little rose', 'Hawaiian', 'Unique'],
  ['Maleko', 'boy', 'Warlike', 'Hawaiian', 'Unique'],
  ['Moku', 'boy', 'Island', 'Hawaiian', 'Unique'],
  ['Nalu', 'boy', 'Wave', 'Hawaiian', 'Unique'],
  ['Peleke', 'boy', 'Peaceful ruler', 'Hawaiian', 'Unique'],
  ['Akela', 'girl', 'Noble, grace', 'Hawaiian', 'Unique'],
  ['Alana', 'girl', 'Awakening, offering', 'Hawaiian', 'Unique'],
  ['Anela', 'girl', 'Angel', 'Hawaiian', 'Unique'],
  ['Haunani', 'girl', 'Beautiful snow', 'Hawaiian', 'Unique'],
  ['Kailani', 'girl', 'Sea and sky', 'Hawaiian', 'Unique'],
  ['Kainoa', 'girl', 'The namesake', 'Hawaiian', 'Unique'],
  ['Kalani', 'girl', 'The heavens, royal', 'Hawaiian', 'Unique'],
  ['Kaipo', 'girl', 'Sweetheart', 'Hawaiian', 'Unique'],
  ['Kamalani', 'girl', 'Heavenly child', 'Hawaiian', 'Unique'],
  ['Kapua', 'girl', 'The flower', 'Hawaiian', 'Unique'],
  ['Kawai', 'girl', 'The water', 'Hawaiian', 'Unique'],
  ['Maile', 'girl', 'Vine, beloved', 'Hawaiian', 'Unique'],
  ['Meilani', 'girl', 'Heavenly flower', 'Hawaiian', 'Unique'],
  ['Miliani', 'girl', 'Soft caress', 'Hawaiian', 'Unique'],
  ['Nohea', 'girl', 'Lovely, beautiful', 'Hawaiian', 'Unique'],
  ['Ohe', 'girl', 'Bamboo', 'Hawaiian', 'Unique'],
  ['Pua', 'girl', 'Flower', 'Hawaiian', 'Unique'],
  ['Ulani', 'girl', 'Cheerful, heaven sent', 'Hawaiian', 'Unique'],
];

export const EXTRA_INDIAN = [
  ['Advik', 'boy', 'Unique, one of a kind', 'Indian', 'Modern'],
  ['Arnav', 'boy', 'Ocean, sea', 'Indian', 'Modern'],
  ['Aryan', 'boy', 'Noble, great warrior', 'Indian', 'Modern'],
  ['Dev', 'boy', 'God, divine', 'Indian', 'Modern'],
  ['Ivaan', 'boy', 'Gracious gift', 'Indian', 'Modern'],
  ['Jay', 'boy', 'Victory, triumph', 'Indian', 'Modern'],
  ['Kiaan', 'boy', 'Gracious, king', 'Indian', 'Modern'],
  ['Nirvaan', 'boy', 'Liberation, peace', 'Indian', 'Unique'],
  ['Riyaan', 'boy', 'Little king, gates of heaven', 'Indian', 'Modern'],
  ['Ryan', 'boy', 'Little king', 'Indian', 'Modern'],
  ['Viaan', 'boy', 'Full of life', 'Indian', 'Modern'],
  ['Vivaan', 'boy', 'Full of life, lord of the sun', 'Indian', 'Modern'],
  ['Aarna', 'girl', 'Goddess Lakshmi, flowing', 'Indian', 'Modern'],
  ['Aarvi', 'girl', 'Peace, prosperous', 'Indian', 'Modern'],
  ['Aanya', 'girl', 'Gracious, resurrection', 'Indian', 'Modern'],
  ['Advika', 'girl', 'Unique, one of a kind', 'Indian', 'Unique'],
  ['Avni', 'girl', 'Earth', 'Indian', 'Modern'],
  ['Ishita', 'girl', 'Supreme, desired', 'Indian', 'Modern'],
  ['Kavya', 'girl', 'Poetry, wisdom', 'Indian', 'Modern'],
  ['Mishika', 'girl', 'Sweet, innocent', 'Indian', 'Unique'],
  ['Nivaan', 'girl', 'Peace', 'Indian', 'Unique'],
  ['Shanvi', 'girl', 'Goddess Lakshmi', 'Indian', 'Modern'],
  ['Suhana', 'girl', 'Beautiful, pleasant', 'Indian', 'Modern'],
  ['Tara', 'girl', 'Star, goddess', 'Indian', 'Modern'],
  ['Vanya', 'girl', 'Gracious, forest', 'Indian', 'Modern'],
];
