// Extra names for small "other" origins to widen letter/style coverage.
// Tuple format: [name, gender, meaning, origin, style]

export const EXTRA_IRISH = [
  ['Aengus', 'boy', 'One strength, single choice', 'Irish', 'Unique'],
  ['Barry', 'boy', 'Fair-haired, spearman', 'Irish', 'Classic'],
  ['Brendan', 'boy', 'Prince, brave', 'Irish', 'Classic'],
  ['Cathal', 'boy', 'Battle ruler', 'Irish', 'Classic'],
  ['Ciaran', 'boy', 'Little dark one', 'Irish', 'Classic'],
  ['Colm', 'boy', 'Dove', 'Irish', 'Classic'],
  ['Cormac', 'boy', 'Charioteer, raven son', 'Irish', 'Classic'],
  ['Darragh', 'boy', 'Oak tree, fruitful', 'Irish', 'Unique'],
  ['Donal', 'boy', 'World ruler, proud chief', 'Irish', 'Classic'],
  ['Eoghan', 'boy', 'Born of the yew tree', 'Irish', 'Unique'],
  ['Finn', 'boy', 'Fair, white, blessed', 'Irish', 'Modern'],
  ['Fintan', 'boy', 'White fire', 'Irish', 'Unique'],
  ['Grady', 'boy', 'Noble, illustrious', 'Irish', 'Unique'],
  ['Keegan', 'boy', 'Little fiery one', 'Irish', 'Modern'],
  ['Killian', 'boy', 'Little church, bright-headed', 'Irish', 'Modern'],
  ['Lorcan', 'boy', 'Little fierce one', 'Irish', 'Unique'],
  ['Malachy', 'boy', 'Messenger of God', 'Irish', 'Classic'],
  ['Oisin', 'boy', 'Little deer', 'Irish', 'Unique'],
  ['Padraig', 'boy', 'Nobleman', 'Irish', 'Classic'],
  ['Quinn', 'boy', 'Descendant of Conn, wise', 'Irish', 'Modern'],
  ['Rory', 'boy', 'Red king, famous ruler', 'Irish', 'Modern'],
  ['Tadhg', 'boy', 'Poet, storyteller', 'Irish', 'Unique'],
  ['Tiernan', 'boy', 'Little lord', 'Irish', 'Unique'],
  ['Aibhilin', 'girl', 'Bright, shining', 'Irish', 'Unique'],
  ['Aoibheann', 'girl', 'Beautiful, radiant', 'Irish', 'Unique'],
  ['Ava', 'girl', 'Life, living one', 'Irish', 'Modern'],
  ['Caitlin', 'girl', 'Pure', 'Irish', 'Classic'],
  ['Clodagh', 'girl', 'River name, gentle', 'Irish', 'Unique'],
  ['Deirdre', 'girl', 'Sorrowful, young', 'Irish', 'Classic'],
  ['Eabha', 'girl', 'Life, living one', 'Irish', 'Unique'],
  ['Eimear', 'girl', 'Swift, beautiful', 'Irish', 'Unique'],
  ['Fiona', 'girl', 'Fair, white', 'Irish', 'Classic'],
  ['Grainne', 'girl', 'Love, grain', 'Irish', 'Unique'],
  ['Kiera', 'girl', 'Little dark one', 'Irish', 'Modern'],
  ['Laoise', 'girl', 'Radiance, light', 'Irish', 'Unique'],
  ['Maeve', 'girl', 'Intoxicating, she who rules', 'Irish', 'Unique'],
  ['Muireann', 'girl', 'Sea fair, bright sea', 'Irish', 'Unique'],
  ['Nessa', 'girl', 'Gentle, not gentle', 'Irish', 'Unique'],
  ['Oonagh', 'girl', 'Lamb, unity', 'Irish', 'Unique'],
  ['Roisin', 'girl', 'Little rose', 'Irish', 'Unique'],
  ['Sinead', 'girl', 'God is gracious', 'Irish', 'Classic'],
  ['Siofra', 'girl', 'Sprite, fairy', 'Irish', 'Unique'],
  ['Treasa', 'girl', 'Strength, harvest', 'Irish', 'Classic'],
];

export const EXTRA_CELTIC = [
  ['Aedan', 'boy', 'Little fire', 'Celtic', 'Unique'],
  ['Brennan', 'boy', 'Little raven, sorrow', 'Celtic', 'Unique'],
  ['Cadmus', 'boy', 'Dragon teeth, founder', 'Celtic', 'Unique'],
  ['Caradoc', 'boy', 'Beloved, amiable', 'Celtic', 'Unique'],
  ['Conlan', 'boy', 'Strong wolf, hero', 'Celtic', 'Unique'],
  ['Dylan', 'boy', 'Son of the sea', 'Celtic', 'Modern'],
  ['Egan', 'boy', 'Little fire', 'Celtic', 'Unique'],
  ['Evan', 'boy', 'God is gracious', 'Celtic', 'Modern'],
  ['Gavin', 'boy', 'White hawk, battle hawk', 'Celtic', 'Modern'],
  ['Glyndwr', 'boy', 'Valley water', 'Celtic', 'Unique'],
  ['Kerrigan', 'boy', 'Dark haired', 'Celtic', 'Unique'],
  ['Llewellyn', 'boy', 'Leader, lion-like', 'Celtic', 'Classic'],
  ['Mael', 'boy', 'Prince, chief', 'Celtic', 'Unique'],
  ['Owen', 'boy', 'Born of the yew tree', 'Celtic', 'Modern'],
  ['Padraig', 'boy', 'Nobleman', 'Celtic', 'Classic'],
  ['Riley', 'boy', 'Courageous, valiant', 'Celtic', 'Modern'],
  ['Tristan', 'boy', 'Sad, sorrowful, knight', 'Celtic', 'Modern'],
  ['Aisling', 'girl', 'Dream, vision', 'Celtic', 'Unique'],
  ['Brangwen', 'girl', 'Dark and pure, blessed raven', 'Celtic', 'Unique'],
  ['Branwen', 'girl', 'Blessed raven', 'Celtic', 'Unique'],
  ['Cadence', 'girl', 'Rhythm, flow', 'Celtic', 'Unique'],
  ['Ceridwen', 'girl', 'Blessed poetry', 'Celtic', 'Unique'],
  ['Cordelia', 'girl', 'Heart, daughter of the sea', 'Celtic', 'Classic'],
  ['Eira', 'girl', 'Snow', 'Celtic', 'Unique'],
  ['Elowen', 'girl', 'Elm tree', 'Celtic', 'Unique'],
  ['Iona', 'girl', 'Island, blessed isle', 'Celtic', 'Unique'],
  ['Kerensa', 'girl', 'Love', 'Celtic', 'Unique'],
  ['Megan', 'girl', 'Pearl', 'Celtic', 'Modern'],
  ['Morwenna', 'girl', 'Waves of the sea', 'Celtic', 'Unique'],
  ['Nerys', 'girl', 'Lady', 'Celtic', 'Unique'],
  ['Rosalind', 'girl', 'Beautiful rose', 'Celtic', 'Classic'],
  ['Shona', 'girl', 'God is gracious', 'Celtic', 'Classic'],
  ['Sulis', 'girl', 'Sun goddess', 'Celtic', 'Unique'],
  ['Winifred', 'girl', 'Blessed peace, friend', 'Celtic', 'Classic'],
];

export const EXTRA_SCOTTISH = [
  ['Alasdair', 'boy', 'Defender of men', 'Scottish', 'Classic'],
  ['Blair', 'boy', 'Field, battlefield', 'Scottish', 'Modern'],
  ['Cameron', 'boy', 'Crooked nose, bent river', 'Scottish', 'Modern'],
  ['Craig', 'boy', 'Rocky hill', 'Scottish', 'Classic'],
  ['Duncan', 'boy', 'Brown warrior', 'Scottish', 'Classic'],
  ['Ewan', 'boy', 'Born of the yew tree', 'Scottish', 'Modern'],
  ['Fergus', 'boy', 'Man of vigour', 'Scottish', 'Classic'],
  ['Graham', 'boy', 'Grey home, gravelly homestead', 'Scottish', 'Classic'],
  ['Greer', 'boy', 'Watchful, guardian', 'Scottish', 'Unique'],
  ['Iain', 'boy', 'God is gracious', 'Scottish', 'Classic'],
  ['Keith', 'boy', 'Wood, forest', 'Scottish', 'Classic'],
  ['Kyle', 'boy', 'Narrow strait, channel', 'Scottish', 'Modern'],
  ['Logan', 'boy', 'Little hollow', 'Scottish', 'Modern'],
  ['Malcolm', 'boy', 'Devotee of Saint Columba', 'Scottish', 'Classic'],
  ['Munro', 'boy', 'Man from the red marsh', 'Scottish', 'Unique'],
  ['Niall', 'boy', 'Champion, cloud', 'Scottish', 'Classic'],
  ['Ross', 'boy', 'Headland, promontory', 'Scottish', 'Classic'],
  ['Rory', 'boy', 'Red king, famous ruler', 'Scottish', 'Modern'],
  ['Tavish', 'boy', 'Twin, beloved', 'Scottish', 'Unique'],
  ['Alana', 'girl', 'Beautiful, fair', 'Scottish', 'Unique'],
  ['Annabel', 'girl', 'Grace, lovable', 'Scottish', 'Classic'],
  ['Bonnie', 'girl', 'Pretty, beautiful', 'Scottish', 'Modern'],
  ['Catriona', 'girl', 'Pure', 'Scottish', 'Classic'],
  ['Elspeth', 'girl', 'God is my oath', 'Scottish', 'Classic'],
  ['Heather', 'girl', 'Heather flower', 'Scottish', 'Classic'],
  ['Kirsty', 'girl', 'Follower of Christ', 'Scottish', 'Classic'],
  ['Lorna', 'girl', 'Lorn, from the wild land', 'Scottish', 'Unique'],
  ['Mairi', 'girl', 'Beloved, bitter', 'Scottish', 'Classic'],
  ['Merryn', 'girl', 'Joyful, light-hearted', 'Scottish', 'Unique'],
  ['Mhairi', 'girl', 'Beloved', 'Scottish', 'Unique'],
  ['Morag', 'girl', 'Great one, sun', 'Scottish', 'Classic'],
  ['Morna', 'girl', 'Beloved, noble', 'Scottish', 'Unique'],
  ['Rowena', 'girl', 'White, fair, joyful', 'Scottish', 'Unique'],
  ['Sorcha', 'girl', 'Bright, radiant', 'Scottish', 'Unique'],
  ['Tegan', 'girl', 'Beautiful, fair', 'Scottish', 'Unique'],
];
