// Extra names for small "other" origins to widen letter/style coverage.
// Tuple format: [name, gender, meaning, origin, style]

export const EXTRA_FRENCH = [
  ['Alexandre', 'boy', 'Defender of men', 'French', 'Classic'],
  ['Baptiste', 'boy', 'Baptised one', 'French', 'Classic'],
  ['Benjamin', 'boy', 'Son of the right hand', 'French', 'Modern'],
  ['Blaise', 'boy', 'Lisping, stammering', 'French', 'Unique'],
  ['Charles', 'boy', 'Strong, free man', 'French', 'Classic'],
  ['Clement', 'boy', 'Merciful, gentle', 'French', 'Classic'],
  ['Damien', 'boy', 'To tame, conquer', 'French', 'Classic'],
  ['Denis', 'boy', 'Follower of Dionysus', 'French', 'Classic'],
  ['Didier', 'boy', 'Desired, wished', 'French', 'Classic'],
  ['Dominique', 'boy', 'Of the Lord', 'French', 'Classic'],
  ['Emile', 'boy', 'Rival, eager', 'French', 'Classic'],
  ['Fabien', 'boy', 'Bean grower', 'French', 'Unique'],
  ['Florian', 'boy', 'Flowering, blooming', 'French', 'Classic'],
  ['Francois', 'boy', 'Frenchman, free one', 'French', 'Classic'],
  ['Gilles', 'boy', 'Young goat, shield bearer', 'French', 'Classic'],
  ['Guillaume', 'boy', 'Resolute protector', 'French', 'Classic'],
  ['Julien', 'boy', 'Youthful', 'French', 'Classic'],
  ['Laurent', 'boy', 'Laurel-crowned', 'French', 'Classic'],
  ['Lionel', 'boy', 'Little lion', 'French', 'Unique'],
  ['Marc', 'boy', 'Warlike', 'French', 'Classic'],
  ['Martin', 'boy', 'Warlike, of Mars', 'French', 'Classic'],
  ['Mathieu', 'boy', 'Gift of God', 'French', 'Classic'],
  ['Maxime', 'boy', 'Greatest', 'French', 'Modern'],
  ['Michel', 'boy', 'Who is like God', 'French', 'Classic'],
  ['Nicolas', 'boy', 'Victory of the people', 'French', 'Classic'],
  ['Olivier', 'boy', 'Olive tree', 'French', 'Classic'],
  ['Pascal', 'boy', 'Of Easter, of Passover', 'French', 'Classic'],
  ['Paul', 'boy', 'Small, humble', 'French', 'Classic'],
  ['Philippe', 'boy', 'Lover of horses', 'French', 'Classic'],
  ['Raphael', 'boy', 'God has healed', 'French', 'Modern'],
  ['Romain', 'boy', 'From Rome', 'French', 'Classic'],
  ['Sebastien', 'boy', 'Venerable, revered', 'French', 'Classic'],
  ['Simon', 'boy', 'Heard, hearkening', 'French', 'Classic'],
  ['Sylvain', 'boy', 'Of the forest', 'French', 'Classic'],
  ['Thibault', 'boy', 'Bold people, brave', 'French', 'Unique'],
  ['Thomas', 'boy', 'Twin', 'French', 'Classic'],
  ['Victor', 'boy', 'Conqueror, victorious', 'French', 'Classic'],
  ['Vincent', 'boy', 'Conquering', 'French', 'Classic'],
  ['Xavier', 'boy', 'New house, bright', 'French', 'Classic'],
  ['Adele', 'girl', 'Noble, kind', 'French', 'Classic'],
  ['Agnes', 'girl', 'Pure, chaste', 'French', 'Classic'],
  ['Alice', 'girl', 'Noble, kind', 'French', 'Modern'],
  ['Aurore', 'girl', 'Dawn', 'French', 'Unique'],
  ['Aurelie', 'girl', 'Golden', 'French', 'Classic'],
  ['Bernadette', 'girl', 'Brave as a bear', 'French', 'Classic'],
  ['Blanche', 'girl', 'White, pure', 'French', 'Classic'],
  ['Carole', 'girl', 'Strong, free man', 'French', 'Classic'],
  ['Cecile', 'girl', 'Blind, musical', 'French', 'Classic'],
  ['Charlotte', 'girl', 'Strong, free man', 'French', 'Classic'],
  ['Christine', 'girl', 'Follower of Christ', 'French', 'Classic'],
  ['Claire', 'girl', 'Bright, clear', 'French', 'Classic'],
  ['Delphine', 'girl', 'Dolphin, from Delphi', 'French', 'Unique'],
  ['Emilie', 'girl', 'Rival, eager', 'French', 'Classic'],
  ['Emmanuelle', 'girl', 'God with us', 'French', 'Classic'],
  ['Francoise', 'girl', 'Free one, from France', 'French', 'Classic'],
  ['Helene', 'girl', 'Bright, shining', 'French', 'Classic'],
  ['Isabelle', 'girl', 'God is my oath, beautiful', 'French', 'Modern'],
  ['Jacqueline', 'girl', 'Supplanter', 'French', 'Classic'],
  ['Jeanne', 'girl', 'God is gracious', 'French', 'Classic'],
  ['Juliette', 'girl', 'Youthful', 'French', 'Modern'],
  ['Laure', 'girl', 'Laurel-crowned', 'French', 'Classic'],
  ['Laurence', 'girl', 'Laurel-crowned', 'French', 'Classic'],
  ['Lea', 'girl', 'Weary, delicate', 'French', 'Modern'],
  ['Louise', 'girl', 'Famous warrior', 'French', 'Classic'],
  ['Madeleine', 'girl', 'High tower', 'French', 'Classic'],
  ['Marie', 'girl', 'Beloved, bitter', 'French', 'Classic'],
  ['Mathilde', 'girl', 'Mighty in battle', 'French', 'Classic'],
  ['Melanie', 'girl', 'Dark, black', 'French', 'Classic'],
  ['Michelle', 'girl', 'Who is like God', 'French', 'Classic'],
  ['Nathalie', 'girl', 'Born at Christmas', 'French', 'Classic'],
  ['Nicole', 'girl', 'Victory of the people', 'French', 'Classic'],
  ['Pauline', 'girl', 'Small, humble', 'French', 'Classic'],
  ['Renee', 'girl', 'Reborn', 'French', 'Classic'],
  ['Sophie', 'girl', 'Wisdom', 'French', 'Modern'],
  ['Sylvie', 'girl', 'Of the forest', 'French', 'Classic'],
  ['Therese', 'girl', 'Harvest, summer', 'French', 'Classic'],
  ['Valerie', 'girl', 'Strong, healthy', 'French', 'Classic'],
  ['Veronique', 'girl', 'True image, bearer of victory', 'French', 'Classic'],
  ['Virginie', 'girl', 'Maiden, pure', 'French', 'Classic'],
];

export const EXTRA_ITALIAN = [
  ['Adamo', 'boy', 'Man of the earth', 'Italian', 'Classic'],
  ['Alberto', 'boy', 'Noble and bright', 'Italian', 'Classic'],
  ['Aldo', 'boy', 'Old, wise, noble', 'Italian', 'Classic'],
  ['Alessio', 'boy', 'Defender of men', 'Italian', 'Modern'],
  ['Alfonso', 'boy', 'Noble and ready', 'Italian', 'Classic'],
  ['Alvaro', 'boy', 'Guardian of all, elf warrior', 'Italian', 'Unique'],
  ['Amedeo', 'boy', 'Loving God', 'Italian', 'Classic'],
  ['Angelo', 'boy', 'Messenger, angel', 'Italian', 'Classic'],
  ['Arturo', 'boy', 'Noble bear', 'Italian', 'Classic'],
  ['Bruno', 'boy', 'Brown, shield', 'Italian', 'Classic'],
  ['Carlo', 'boy', 'Strong, free man', 'Italian', 'Classic'],
  ['Cesare', 'boy', 'Hairy, long-haired', 'Italian', 'Classic'],
  ['Claudio', 'boy', 'Lame', 'Italian', 'Classic'],
  ['Damiano', 'boy', 'To tame, conquer', 'Italian', 'Classic'],
  ['Dario', 'boy', 'Possessor of goodness', 'Italian', 'Classic'],
  ['Davide', 'boy', 'Beloved', 'Italian', 'Classic'],
  ['Edoardo', 'boy', 'Wealthy guardian', 'Italian', 'Classic'],
  ['Emanuele', 'boy', 'God with us', 'Italian', 'Classic'],
  ['Ettore', 'boy', 'Holding fast, steadfast', 'Italian', 'Classic'],
  ['Federico', 'boy', 'Peaceful ruler', 'Italian', 'Classic'],
  ['Filippo', 'boy', 'Lover of horses', 'Italian', 'Classic'],
  ['Giacomo', 'boy', 'Supplanter', 'Italian', 'Classic'],
  ['Giorgio', 'boy', 'Farmer, earthworker', 'Italian', 'Classic'],
  ['Giuseppe', 'boy', 'God increases', 'Italian', 'Classic'],
  ['Guido', 'boy', 'Wood, forest, guide', 'Italian', 'Classic'],
  ['Lamberto', 'boy', 'Bright land', 'Italian', 'Unique'],
  ['Lazzaro', 'boy', 'God has helped', 'Italian', 'Classic'],
  ['Leo', 'boy', 'Lion', 'Italian', 'Modern'],
  ['Leone', 'boy', 'Lion', 'Italian', 'Unique'],
  ['Lino', 'boy', 'Flax, linen', 'Italian', 'Modern'],
  ['Lio', 'boy', 'Follower of the people', 'Italian', 'Modern'],
  ['Loris', 'boy', 'Laurel-crowned', 'Italian', 'Modern'],
  ['Ludovico', 'boy', 'Famous warrior', 'Italian', 'Modern'],
  ['Luigi', 'boy', 'Famous warrior', 'Italian', 'Classic'],
  ['Luciano', 'boy', 'Light', 'Italian', 'Classic'],
  ['Lucio', 'boy', 'Light', 'Italian', 'Classic'],
  ['Livio', 'boy', 'Bluish, envious', 'Italian', 'Unique'],
  ['Mario', 'boy', 'Of Mars, warlike', 'Italian', 'Classic'],
  ['Nicola', 'boy', 'Victory of the people', 'Italian', 'Classic'],
  ['Nino', 'boy', 'God is gracious', 'Italian', 'Unique'],
  ['Paolo', 'boy', 'Small, humble', 'Italian', 'Classic'],
  ['Pietro', 'boy', 'Rock, stone', 'Italian', 'Classic'],
  ['Riccardo', 'boy', 'Brave ruler', 'Italian', 'Classic'],
  ['Roberto', 'boy', 'Bright fame', 'Italian', 'Classic'],
  ['Salvatore', 'boy', 'Saviour, rescuer', 'Italian', 'Classic'],
  ['Samuele', 'boy', 'Heard by God', 'Italian', 'Classic'],
  ['Silvio', 'boy', 'Of the forest', 'Italian', 'Classic'],
  ['Simone', 'boy', 'Heard, hearkening', 'Italian', 'Classic'],
  ['Stefano', 'boy', 'Crown, garland', 'Italian', 'Classic'],
  ['Tommaso', 'boy', 'Twin', 'Italian', 'Classic'],
  ['Vincenzo', 'boy', 'Conquering', 'Italian', 'Classic'],
  ['Vittorio', 'boy', 'Victorious', 'Italian', 'Classic'],
  ['Adriana', 'girl', 'From Hadria, dark one', 'Italian', 'Classic'],
  ['Alessandra', 'girl', 'Defender of men', 'Italian', 'Classic'],
  ['Alice', 'girl', 'Noble, kind', 'Italian', 'Modern'],
  ['Ambra', 'girl', 'Amber, glowing', 'Italian', 'Unique'],
  ['Angela', 'girl', 'Messenger, angel', 'Italian', 'Classic'],
  ['Anna', 'girl', 'Grace, favour', 'Italian', 'Classic'],
  ['Antonella', 'girl', 'Priceless, praiseworthy', 'Italian', 'Classic'],
  ['Beatrice', 'girl', 'She who brings happiness', 'Italian', 'Classic'],
  ['Camilla', 'girl', 'Attendant, young ceremonial', 'Italian', 'Classic'],
  ['Carlotta', 'girl', 'Strong, free man', 'Italian', 'Classic'],
  ['Caterina', 'girl', 'Pure', 'Italian', 'Classic'],
  ['Cecilia', 'girl', 'Blind, musical', 'Italian', 'Classic'],
  ['Clara', 'girl', 'Bright, clear', 'Italian', 'Classic'],
  ['Claudia', 'girl', 'Lame, noble', 'Italian', 'Classic'],
  ['Cristina', 'girl', 'Follower of Christ', 'Italian', 'Classic'],
  ['Daniela', 'girl', 'God is my judge', 'Italian', 'Classic'],
  ['Elisa', 'girl', 'God is my oath', 'Italian', 'Modern'],
  ['Emma', 'girl', 'Whole, universal', 'Italian', 'Modern'],
  ['Federica', 'girl', 'Peaceful ruler', 'Italian', 'Classic'],
  ['Francesca', 'girl', 'Free one, from France', 'Italian', 'Classic'],
  ['Gaia', 'girl', 'Earth', 'Italian', 'Unique'],
  ['Giorgia', 'girl', 'Farmer, earthworker', 'Italian', 'Classic'],
  ['Giovanna', 'girl', 'God is gracious', 'Italian', 'Classic'],
  ['Giulia', 'girl', 'Youthful', 'Italian', 'Modern'],
  ['Ilaria', 'girl', 'Cheerful, joyful', 'Italian', 'Classic'],
  ['Lara', 'girl', 'Laurel, protection', 'Italian', 'Modern'],
  ['Laura', 'girl', 'Laurel-crowned', 'Italian', 'Classic'],
  ['Letizia', 'girl', 'Joy, gladness', 'Italian', 'Modern'],
  ['Liliana', 'girl', 'Lily flower', 'Italian', 'Classic'],
  ['Lisa', 'girl', 'God is my oath', 'Italian', 'Modern'],
  ['Livia', 'girl', 'Bluish, envious', 'Italian', 'Classic'],
  ['Ludovica', 'girl', 'Famous warrior', 'Italian', 'Modern'],
  ['Lucrezia', 'girl', 'Wealth, gain', 'Italian', 'Unique'],
  ['Luna', 'girl', 'Moon', 'Italian', 'Modern'],
  ['Margherita', 'girl', 'Pearl, daisy flower', 'Italian', 'Classic'],
  ['Maria', 'girl', 'Beloved, bitter', 'Italian', 'Classic'],
  ['Marta', 'girl', 'Lady, mistress', 'Italian', 'Classic'],
  ['Matilde', 'girl', 'Mighty in battle', 'Italian', 'Classic'],
  ['Monica', 'girl', 'Advisor, alone', 'Italian', 'Classic'],
  ['Nadia', 'girl', 'Hope', 'Italian', 'Unique'],
  ['Paola', 'girl', 'Small, humble', 'Italian', 'Classic'],
  ['Raffaella', 'girl', 'God has healed', 'Italian', 'Classic'],
  ['Roberta', 'girl', 'Bright fame', 'Italian', 'Classic'],
  ['Rosaria', 'girl', 'Rose garland', 'Italian', 'Classic'],
  ['Serena', 'girl', 'Calm, tranquil', 'Italian', 'Modern'],
  ['Silvia', 'girl', 'Of the forest', 'Italian', 'Classic'],
  ['Simona', 'girl', 'Heard, hearkening', 'Italian', 'Classic'],
  ['Stefania', 'girl', 'Crown, garland', 'Italian', 'Classic'],
  ['Vittoria', 'girl', 'Victory', 'Italian', 'Classic'],
];
