// Extra names for small "other" origins to widen letter/style coverage.
// Tuple format: [name, gender, meaning, origin, style]

export const EXTRA_SPANISH = [
  ['Adan', 'boy', 'Man of the earth', 'Spanish', 'Classic'],
  ['Agustin', 'boy', 'Great, majestic', 'Spanish', 'Classic'],
  ['Alberto', 'boy', 'Noble and bright', 'Spanish', 'Classic'],
  ['Alfonso', 'boy', 'Noble and ready', 'Spanish', 'Classic'],
  ['Alonso', 'boy', 'Noble and ready', 'Spanish', 'Classic'],
  ['Andres', 'boy', 'Manly, brave', 'Spanish', 'Classic'],
  ['Antonio', 'boy', 'Priceless, praiseworthy', 'Spanish', 'Classic'],
  ['Arturo', 'boy', 'Noble bear', 'Spanish', 'Classic'],
  ['Bruno', 'boy', 'Brown, shield', 'Spanish', 'Modern'],
  ['Cesar', 'boy', 'Hairy, long-haired', 'Spanish', 'Classic'],
  ['Cristian', 'boy', 'Follower of Christ', 'Spanish', 'Modern'],
  ['Daniel', 'boy', 'God is my judge', 'Spanish', 'Classic'],
  ['David', 'boy', 'Beloved', 'Spanish', 'Classic'],
  ['Eduardo', 'boy', 'Wealthy guardian', 'Spanish', 'Classic'],
  ['Emilio', 'boy', 'Rival, eager', 'Spanish', 'Classic'],
  ['Enrique', 'boy', 'Home ruler', 'Spanish', 'Classic'],
  ['Esteban', 'boy', 'Crown, garland', 'Spanish', 'Classic'],
  ['Felipe', 'boy', 'Lover of horses', 'Spanish', 'Classic'],
  ['Francisco', 'boy', 'Free one, from France', 'Spanish', 'Classic'],
  ['Gonzalo', 'boy', 'Battle genius, war', 'Spanish', 'Classic'],
  ['Guillermo', 'boy', 'Resolute protector', 'Spanish', 'Classic'],
  ['Ignacio', 'boy', 'Fiery one', 'Spanish', 'Classic'],
  ['Ivan', 'boy', 'God is gracious', 'Spanish', 'Modern'],
  ['Jaime', 'boy', 'Supplanter', 'Spanish', 'Classic'],
  ['Jesus', 'boy', 'God saves', 'Spanish', 'Classic'],
  ['Joaquin', 'boy', 'God will establish', 'Spanish', 'Classic'],
  ['Jose', 'boy', 'God increases', 'Spanish', 'Classic'],
  ['Juan', 'boy', 'God is gracious', 'Spanish', 'Classic'],
  ['Julian', 'boy', 'Youthful', 'Spanish', 'Classic'],
  ['Lorenzo', 'boy', 'Laurel-crowned', 'Spanish', 'Classic'],
  ['Luis', 'boy', 'Famous warrior', 'Spanish', 'Classic'],
  ['Marco', 'boy', 'Warlike', 'Spanish', 'Modern'],
  ['Mario', 'boy', 'Of Mars, warlike', 'Spanish', 'Classic'],
  ['Martin', 'boy', 'Warlike, of Mars', 'Spanish', 'Classic'],
  ['Mauricio', 'boy', 'Dark-skinned, Moorish', 'Spanish', 'Classic'],
  ['Mauro', 'boy', 'Dark-skinned, Moorish', 'Spanish', 'Unique'],
  ['Nicolas', 'boy', 'Victory of the people', 'Spanish', 'Classic'],
  ['Oscar', 'boy', 'God spear', 'Spanish', 'Classic'],
  ['Pedro', 'boy', 'Rock, stone', 'Spanish', 'Classic'],
  ['Ramon', 'boy', 'Wise protector', 'Spanish', 'Classic'],
  ['Ricardo', 'boy', 'Brave ruler', 'Spanish', 'Classic'],
  ['Roberto', 'boy', 'Bright fame', 'Spanish', 'Classic'],
  ['Rodrigo', 'boy', 'Famous ruler', 'Spanish', 'Classic'],
  ['Salvador', 'boy', 'Saviour', 'Spanish', 'Classic'],
  ['Samuel', 'boy', 'Heard by God', 'Spanish', 'Classic'],
  ['Sergio', 'boy', 'Servant, attendant', 'Spanish', 'Classic'],
  ['Tomas', 'boy', 'Twin', 'Spanish', 'Classic'],
  ['Valentin', 'boy', 'Strong, healthy', 'Spanish', 'Classic'],
  ['Vicente', 'boy', 'Conquering', 'Spanish', 'Classic'],
  ['Alba', 'girl', 'Dawn, white', 'Spanish', 'Modern'],
  ['Alejandra', 'girl', 'Defender of men', 'Spanish', 'Classic'],
  ['Alma', 'girl', 'Soul, nurturing', 'Spanish', 'Unique'],
  ['Ana', 'girl', 'Grace, favour', 'Spanish', 'Classic'],
  ['Andrea', 'girl', 'Manly, brave', 'Spanish', 'Modern'],
  ['Antonia', 'girl', 'Priceless, praiseworthy', 'Spanish', 'Classic'],
  ['Beatriz', 'girl', 'She who brings happiness', 'Spanish', 'Classic'],
  ['Carolina', 'girl', 'Strong, free man', 'Spanish', 'Classic'],
  ['Catalina', 'girl', 'Pure', 'Spanish', 'Classic'],
  ['Claudia', 'girl', 'Lame, noble', 'Spanish', 'Classic'],
  ['Cristina', 'girl', 'Follower of Christ', 'Spanish', 'Classic'],
  ['Dolores', 'girl', 'Sorrows, lady of pain', 'Spanish', 'Classic'],
  ['Elvira', 'girl', 'Truth, all true', 'Spanish', 'Unique'],
  ['Emilia', 'girl', 'Rival, eager', 'Spanish', 'Classic'],
  ['Esperanza', 'girl', 'Hope', 'Spanish', 'Classic'],
  ['Estrella', 'girl', 'Star', 'Spanish', 'Unique'],
  ['Eva', 'girl', 'Life, living one', 'Spanish', 'Classic'],
  ['Fatima', 'girl', 'Captivating, one who abstains', 'Spanish', 'Classic'],
  ['Fernanda', 'girl', 'Bold voyager', 'Spanish', 'Classic'],
  ['Florencia', 'girl', 'Flourishing, blooming', 'Spanish', 'Classic'],
  ['Gloria', 'girl', 'Glory, praise', 'Spanish', 'Classic'],
  ['Gracia', 'girl', 'Grace, thanks', 'Spanish', 'Unique'],
  ['Guadalupe', 'girl', 'River of the wolf', 'Spanish', 'Classic'],
  ['Ines', 'girl', 'Pure, chaste', 'Spanish', 'Classic'],
  ['Irene', 'girl', 'Peace', 'Spanish', 'Classic'],
  ['Josefina', 'girl', 'God increases', 'Spanish', 'Classic'],
  ['Julia', 'girl', 'Youthful', 'Spanish', 'Modern'],
  ['Julieta', 'girl', 'Youthful', 'Spanish', 'Unique'],
  ['Laura', 'girl', 'Laurel-crowned', 'Spanish', 'Classic'],
  ['Lorena', 'girl', 'Laurel-crowned', 'Spanish', 'Modern'],
  ['Luisa', 'girl', 'Famous warrior', 'Spanish', 'Classic'],
  ['Magdalena', 'girl', 'High tower', 'Spanish', 'Classic'],
  ['Manuela', 'girl', 'God with us', 'Spanish', 'Classic'],
  ['Mariana', 'girl', 'Beloved, bitter', 'Spanish', 'Modern'],
  ['Marta', 'girl', 'Lady, mistress', 'Spanish', 'Classic'],
  ['Natalia', 'girl', 'Born at Christmas', 'Spanish', 'Modern'],
  ['Nuria', 'girl', 'Fire of the Lord', 'Spanish', 'Classic'],
  ['Paloma', 'girl', 'Dove', 'Spanish', 'Classic'],
  ['Patricia', 'girl', 'Noble, patrician', 'Spanish', 'Classic'],
  ['Paula', 'girl', 'Small, humble', 'Spanish', 'Classic'],
  ['Pilar', 'girl', 'Pillar, column', 'Spanish', 'Classic'],
  ['Raquel', 'girl', 'Ewe, innocent', 'Spanish', 'Classic'],
  ['Rosa', 'girl', 'Rose flower', 'Spanish', 'Classic'],
  ['Rosalia', 'girl', 'Rose festival', 'Spanish', 'Classic'],
  ['Sara', 'girl', 'Princess', 'Spanish', 'Classic'],
  ['Silvia', 'girl', 'Of the forest', 'Spanish', 'Classic'],
  ['Teresa', 'girl', 'Harvest, summer', 'Spanish', 'Classic'],
  ['Veronica', 'girl', 'True image, bearer of victory', 'Spanish', 'Classic'],
  ['Victoria', 'girl', 'Victory', 'Spanish', 'Classic'],
];

export const EXTRA_GERMAN = [
  ['Adrian', 'boy', 'From Hadria, dark one', 'German', 'Classic'],
  ['Alexander', 'boy', 'Defender of men', 'German', 'Classic'],
  ['Andreas', 'boy', 'Manly, brave', 'German', 'Classic'],
  ['Anton', 'boy', 'Priceless, praiseworthy', 'German', 'Classic'],
  ['Arne', 'boy', 'Eagle ruler', 'German', 'Unique'],
  ['Benedikt', 'boy', 'Blessed', 'German', 'Classic'],
  ['Bernhard', 'boy', 'Brave as a bear', 'German', 'Classic'],
  ['Carl', 'boy', 'Strong, free man', 'German', 'Classic'],
  ['Christian', 'boy', 'Follower of Christ', 'German', 'Classic'],
  ['Christoph', 'boy', 'Bearer of Christ', 'German', 'Classic'],
  ['Clemens', 'boy', 'Merciful, gentle', 'German', 'Classic'],
  ['Daniel', 'boy', 'God is my judge', 'German', 'Classic'],
  ['Dieter', 'boy', 'Army of the people', 'German', 'Classic'],
  ['Emil', 'boy', 'Rival, eager', 'German', 'Modern'],
  ['Ernst', 'boy', 'Earnest, serious', 'German', 'Classic'],
  ['Felix', 'boy', 'Lucky, happy', 'German', 'Modern'],
  ['Florian', 'boy', 'Flowering, blooming', 'German', 'Classic'],
  ['Franz', 'boy', 'Free one, from France', 'German', 'Classic'],
  ['Georg', 'boy', 'Farmer, earthworker', 'German', 'Classic'],
  ['Gerhard', 'boy', 'Spear brave', 'German', 'Classic'],
  ['Gottfried', 'boy', 'God\'s peace', 'German', 'Classic'],
  ['Heinrich', 'boy', 'Home ruler', 'German', 'Classic'],
  ['Helmut', 'boy', 'Helmet, brave protector', 'German', 'Classic'],
  ['Hermann', 'boy', 'Army man, warrior', 'German', 'Classic'],
  ['Jakob', 'boy', 'Supplanter', 'German', 'Classic'],
  ['Jan', 'boy', 'God is gracious', 'German', 'Modern'],
  ['Jonas', 'boy', 'Dove', 'German', 'Modern'],
  ['Jorg', 'boy', 'Farmer, earthworker', 'German', 'Classic'],
  ['Karl', 'boy', 'Strong, free man', 'German', 'Classic'],
  ['Konrad', 'boy', 'Bold counsel', 'German', 'Classic'],
  ['Leander', 'boy', 'Lion of a man', 'German', 'Unique'],
  ['Leo', 'boy', 'Lion', 'German', 'Modern'],
  ['Leon', 'boy', 'Lion', 'German', 'Modern'],
  ['Lucas', 'boy', 'Bringer of light', 'German', 'Modern'],
  ['Lukas', 'boy', 'Bringer of light', 'German', 'Modern'],
  ['Martin', 'boy', 'Warlike, of Mars', 'German', 'Classic'],
  ['Matthias', 'boy', 'Gift of God', 'German', 'Classic'],
  ['Niklas', 'boy', 'Victory of the people', 'German', 'Modern'],
  ['Paul', 'boy', 'Small, humble', 'German', 'Classic'],
  ['Peter', 'boy', 'Rock, stone', 'German', 'Classic'],
  ['Philip', 'boy', 'Lover of horses', 'German', 'Classic'],
  ['Rainer', 'boy', 'Mighty army', 'German', 'Classic'],
  ['Reinhard', 'boy', 'Bold counsel', 'German', 'Classic'],
  ['Rudolf', 'boy', 'Famous wolf', 'German', 'Classic'],
  ['Stefan', 'boy', 'Crown, garland', 'German', 'Classic'],
  ['Tobias', 'boy', 'God is good', 'German', 'Classic'],
  ['Ulrich', 'boy', 'Wealthy ruler', 'German', 'Classic'],
  ['Walter', 'boy', 'Ruler of the army', 'German', 'Classic'],
  ['Werner', 'boy', 'Protecting army', 'German', 'Classic'],
  ['Amelie', 'girl', 'Work, effort, striving', 'German', 'Modern'],
  ['Anna', 'girl', 'Grace, favour', 'German', 'Classic'],
  ['Barbara', 'girl', 'Foreign, strange', 'German', 'Classic'],
  ['Birgit', 'girl', 'Exalted one, strong', 'German', 'Classic'],
  ['Caroline', 'girl', 'Strong, free man', 'German', 'Classic'],
  ['Charlotte', 'girl', 'Strong, free man', 'German', 'Classic'],
  ['Christina', 'girl', 'Follower of Christ', 'German', 'Classic'],
  ['Clara', 'girl', 'Bright, clear', 'German', 'Modern'],
  ['Dorothea', 'girl', 'Gift of God', 'German', 'Classic'],
  ['Emilia', 'girl', 'Rival, eager', 'German', 'Modern'],
  ['Emma', 'girl', 'Whole, universal', 'German', 'Modern'],
  ['Erika', 'girl', 'Ever ruler', 'German', 'Classic'],
  ['Frieda', 'girl', 'Peaceful ruler', 'German', 'Classic'],
  ['Gisela', 'girl', 'Pledge, hostage', 'German', 'Classic'],
  ['Hannah', 'girl', 'Grace, favour', 'German', 'Modern'],
  ['Helena', 'girl', 'Bright, shining', 'German', 'Classic'],
  ['Hilda', 'girl', 'Battle, battle woman', 'German', 'Classic'],
  ['Ilse', 'girl', 'God is my oath', 'German', 'Classic'],
  ['Johanna', 'girl', 'God is gracious', 'German', 'Classic'],
  ['Julia', 'girl', 'Youthful', 'German', 'Modern'],
  ['Katharina', 'girl', 'Pure', 'German', 'Classic'],
  ['Lena', 'girl', 'Bright, shining', 'German', 'Modern'],
  ['Liesl', 'girl', 'God is my oath', 'German', 'Unique'],
  ['Lilli', 'girl', 'Lily flower', 'German', 'Modern'],
  ['Lotte', 'girl', 'Strong, free man', 'German', 'Unique'],
  ['Luise', 'girl', 'Famous warrior', 'German', 'Classic'],
  ['Marlene', 'girl', 'Star of the sea', 'German', 'Classic'],
  ['Mathilde', 'girl', 'Mighty in battle', 'German', 'Classic'],
  ['Melanie', 'girl', 'Dark, black', 'German', 'Classic'],
  ['Miriam', 'girl', 'Wished-for child, bitter sea', 'German', 'Classic'],
  ['Nina', 'girl', 'Grace, favour', 'German', 'Modern'],
  ['Petra', 'girl', 'Rock, stone', 'German', 'Classic'],
  ['Sabine', 'girl', 'Sabine woman', 'German', 'Classic'],
  ['Stefanie', 'girl', 'Crown, garland', 'German', 'Classic'],
  ['Susanne', 'girl', 'Lily, rose', 'German', 'Classic'],
  ['Ursula', 'girl', 'Little she-bear', 'German', 'Classic'],
  ['Verena', 'girl', 'True, protective', 'German', 'Classic'],
];
