// Extra names for small "other" origins to widen letter/style coverage.
// Tuple format: [name, gender, meaning, origin, style]

export const EXTRA_SCANDINAVIAN = [
  ['Aksel', 'boy', 'Father of peace', 'Scandinavian', 'Unique'],
  ['Alarik', 'boy', 'Ruler of all', 'Scandinavian', 'Unique'],
  ['Arvid', 'boy', 'Eagle tree', 'Scandinavian', 'Unique'],
  ['Axel', 'boy', 'Father of peace', 'Scandinavian', 'Modern'],
  ['Birger', 'boy', 'Helper, rescuer', 'Scandinavian', 'Classic'],
  ['Casper', 'boy', 'Treasurer, keeper of treasure', 'Scandinavian', 'Modern'],
  ['Christian', 'boy', 'Follower of Christ', 'Scandinavian', 'Classic'],
  ['Emil', 'boy', 'Rival, eager', 'Scandinavian', 'Modern'],
  ['Elias', 'boy', 'The Lord is my God', 'Scandinavian', 'Modern'],
  ['Eskil', 'boy', 'God\'s helmet', 'Scandinavian', 'Unique'],
  ['Even', 'boy', 'Gift of God, lucky', 'Scandinavian', 'Unique'],
  ['Filip', 'boy', 'Lover of horses', 'Scandinavian', 'Classic'],
  ['Fredrik', 'boy', 'Peaceful ruler', 'Scandinavian', 'Classic'],
  ['Gunnar', 'boy', 'War, warrior', 'Scandinavian', 'Classic'],
  ['Henrik', 'boy', 'Home ruler', 'Scandinavian', 'Classic'],
  ['Ingvar', 'boy', 'Protected by the god', 'Scandinavian', 'Unique'],
  ['Isak', 'boy', 'He will laugh', 'Scandinavian', 'Modern'],
  ['Johan', 'boy', 'God is gracious', 'Scandinavian', 'Classic'],
  ['Kalle', 'boy', 'Strong, free man', 'Scandinavian', 'Unique'],
  ['Kasper', 'boy', 'Treasurer, keeper of treasure', 'Scandinavian', 'Unique'],
  ['Leif', 'boy', 'Heir, descendant', 'Scandinavian', 'Classic'],
  ['Lennart', 'boy', 'Brave as a lion', 'Scandinavian', 'Classic'],
  ['Linus', 'boy', 'Flax, linen', 'Scandinavian', 'Modern'],
  ['Mikael', 'boy', 'Who is like God', 'Scandinavian', 'Classic'],
  ['Niklas', 'boy', 'Victory of the people', 'Scandinavian', 'Modern'],
  ['Oskar', 'boy', 'God spear', 'Scandinavian', 'Modern'],
  ['Ragnar', 'boy', 'Warrior of judgement', 'Scandinavian', 'Unique'],
  ['Stellan', 'boy', 'Calm, peaceful', 'Scandinavian', 'Unique'],
  ['Torsten', 'boy', 'Thor\'s stone', 'Scandinavian', 'Classic'],
  ['Viggo', 'boy', 'War, battle', 'Scandinavian', 'Unique'],
  ['Vilhelm', 'boy', 'Resolute protector', 'Scandinavian', 'Classic'],
  ['Aino', 'girl', 'The only one', 'Scandinavian', 'Unique'],
  ['Alva', 'girl', 'Elf, supernatural being', 'Scandinavian', 'Modern'],
  ['Birgit', 'girl', 'Exalted one, strong', 'Scandinavian', 'Classic'],
  ['Elise', 'girl', 'God is my oath', 'Scandinavian', 'Modern'],
  ['Ebba', 'girl', 'Strong, lucky', 'Scandinavian', 'Unique'],
  ['Embla', 'girl', 'First woman, elm tree', 'Scandinavian', 'Unique'],
  ['Greta', 'girl', 'Pearl', 'Scandinavian', 'Modern'],
  ['Hanna', 'girl', 'Grace, favour', 'Scandinavian', 'Classic'],
  ['Helga', 'girl', 'Holy, blessed', 'Scandinavian', 'Classic'],
  ['Ida', 'girl', 'Industrious, prosperous', 'Scandinavian', 'Modern'],
  ['Karin', 'girl', 'Pure', 'Scandinavian', 'Classic'],
  ['Katrine', 'girl', 'Pure', 'Scandinavian', 'Classic'],
  ['Livia', 'girl', 'Bluish, envious', 'Scandinavian', 'Unique'],
  ['Liv', 'girl', 'Life, protection', 'Scandinavian', 'Unique'],
  ['Maja', 'girl', 'Pearl, bitter', 'Scandinavian', 'Modern'],
  ['Matilda', 'girl', 'Mighty in battle', 'Scandinavian', 'Classic'],
  ['Nanna', 'girl', 'Bold, courageous', 'Scandinavian', 'Unique'],
  ['Nora', 'girl', 'Light, honour', 'Scandinavian', 'Modern'],
  ['Signe', 'girl', 'New victory', 'Scandinavian', 'Unique'],
  ['Sigrid', 'girl', 'Beautiful victory', 'Scandinavian', 'Classic'],
  ['Siv', 'girl', 'Bride, wife', 'Scandinavian', 'Unique'],
  ['Sofie', 'girl', 'Wisdom', 'Scandinavian', 'Modern'],
  ['Tove', 'girl', 'Thunder, beautiful', 'Scandinavian', 'Unique'],
  ['Viktoria', 'girl', 'Victory', 'Scandinavian', 'Classic'],
];

export const EXTRA_PERSIAN = [
  ['Ardalan', 'boy', 'Virtuous, noble', 'Persian', 'Unique'],
  ['Arash', 'boy', 'Bright, truthful archer', 'Persian', 'Unique'],
  ['Aryo', 'boy', 'Noble, Aryan', 'Persian', 'Unique'],
  ['Bahram', 'boy', 'Victorious, god of victory', 'Persian', 'Classic'],
  ['Behnam', 'boy', 'Excellent, noble', 'Persian', 'Classic'],
  ['Behruz', 'boy', 'Fortunate, good day', 'Persian', 'Unique'],
  ['Dara', 'boy', 'Wealth, royal', 'Persian', 'Classic'],
  ['Ebrahim', 'boy', 'Father of nations', 'Persian', 'Classic'],
  ['Farid', 'boy', 'Unique, precious', 'Persian', 'Unique'],
  ['Farshad', 'boy', 'Joyful, happy', 'Persian', 'Classic'],
  ['Fereydoun', 'boy', 'Victorious king', 'Persian', 'Classic'],
  ['Golzar', 'boy', 'Rose garden', 'Persian', 'Unique'],
  ['Hamed', 'boy', 'Praiseworthy', 'Persian', 'Classic'],
  ['Hossein', 'boy', 'Handsome, good', 'Persian', 'Classic'],
  ['Iman', 'boy', 'Faith, belief', 'Persian', 'Modern'],
  ['Kamran', 'boy', 'Successful, prosperous', 'Persian', 'Classic'],
  ['Kaveh', 'boy', 'Royal, glorious', 'Persian', 'Unique'],
  ['Khosrow', 'boy', 'Famous, well-renowned', 'Persian', 'Classic'],
  ['Mahdi', 'boy', 'Guided one', 'Persian', 'Classic'],
  ['Mahan', 'boy', 'Moonlike, great', 'Persian', 'Unique'],
  ['Maziar', 'boy', 'Governor of the province', 'Persian', 'Unique'],
  ['Navid', 'boy', 'Good news', 'Persian', 'Unique'],
  ['Nima', 'boy', 'Just, fair', 'Persian', 'Unique'],
  ['Parham', 'boy', 'Supreme, great ruler', 'Persian', 'Unique'],
  ['Payam', 'boy', 'Message, good news', 'Persian', 'Unique'],
  ['Rostam', 'boy', 'Hero, brave', 'Persian', 'Classic'],
  ['Sam', 'boy', 'Elevated, exalted', 'Persian', 'Unique'],
  ['Shahram', 'boy', 'King of kings', 'Persian', 'Classic'],
  ['Shayan', 'boy', 'Worthy, deserving', 'Persian', 'Unique'],
  ['Sina', 'boy', 'Treasure, splendour', 'Persian', 'Unique'],
  ['Vahid', 'boy', 'Unique, singular', 'Persian', 'Classic'],
  ['Yousef', 'boy', 'God increases', 'Persian', 'Classic'],
  ['Zubin', 'boy', 'Powerful, strong', 'Persian', 'Unique'],
  ['Afsaneh', 'girl', 'Fable, legend', 'Persian', 'Unique'],
  ['Anousheh', 'girl', 'Immortal', 'Persian', 'Unique'],
  ['Armina', 'girl', 'Pure, dear', 'Persian', 'Unique'],
  ['Asal', 'girl', 'Honey', 'Persian', 'Unique'],
  ['Ava', 'girl', 'Voice, sound', 'Persian', 'Modern'],
  ['Bahar', 'girl', 'Spring', 'Persian', 'Unique'],
  ['Donya', 'girl', 'World', 'Persian', 'Unique'],
  ['Elnaz', 'girl', 'Sweetheart, elegant', 'Persian', 'Unique'],
  ['Farah', 'girl', 'Joy, happiness', 'Persian', 'Classic'],
  ['Farnaz', 'girl', 'Royal, graceful', 'Persian', 'Unique'],
  ['Golnaz', 'girl', 'Rose, flowerlike', 'Persian', 'Unique'],
  ['Kiana', 'girl', 'Ancient queen', 'Persian', 'Unique'],
  ['Mahsa', 'girl', 'Moonlike', 'Persian', 'Unique'],
  ['Marjan', 'girl', 'Coral, pearl', 'Persian', 'Unique'],
  ['Maryam', 'girl', 'Beloved, bitter', 'Persian', 'Classic'],
  ['Mina', 'girl', 'Azure, enamelled glass', 'Persian', 'Classic'],
  ['Mitra', 'girl', 'Goddess of the sun, friendship', 'Persian', 'Classic'],
  ['Nazanin', 'girl', 'Sweetheart, beloved', 'Persian', 'Unique'],
  ['Niloufar', 'girl', 'Lotus, water lily', 'Persian', 'Unique'],
  ['Niloofar', 'girl', 'Lotus, water lily', 'Persian', 'Unique'],
  ['Parisa', 'girl', 'Fairy-like', 'Persian', 'Unique'],
  ['Parvaneh', 'girl', 'Butterfly', 'Persian', 'Unique'],
  ['Roshan', 'girl', 'Bright, light', 'Persian', 'Unique'],
  ['Sahar', 'girl', 'Dawn', 'Persian', 'Unique'],
  ['Setareh', 'girl', 'Star', 'Persian', 'Unique'],
  ['Shabnam', 'girl', 'Morning dew', 'Persian', 'Unique'],
  ['Sima', 'girl', 'Face, image', 'Persian', 'Unique'],
  ['Sogol', 'girl', 'Flower', 'Persian', 'Unique'],
  ['Tara', 'girl', 'Star', 'Persian', 'Modern'],
  ['Yasaman', 'girl', 'Jasmine flower', 'Persian', 'Unique'],
];
