// Extra names for small "other" origins to widen letter/style coverage.
// Tuple format: [name, gender, meaning, origin, style]
// These are merged into OTHER in build-names.mjs.

export const EXTRA_GREEK = [
  ['Achilleas', 'boy', 'Pain, protector of men', 'Greek', 'Classic'],
  ['Adamos', 'boy', 'Man of the earth', 'Greek', 'Unique'],
  ['Alexandros', 'boy', 'Defender of men', 'Greek', 'Classic'],
  ['Ambrose', 'boy', 'Immortal, divine', 'Greek', 'Unique'],
  ['Angelos', 'boy', 'Messenger, angel', 'Greek', 'Classic'],
  ['Antonis', 'boy', 'Priceless, praiseworthy', 'Greek', 'Modern'],
  ['Apostolos', 'boy', 'Apostle, messenger', 'Greek', 'Classic'],
  ['Aris', 'boy', 'Best, ideal', 'Greek', 'Modern'],
  ['Aristides', 'boy', 'Best, son of the best', 'Greek', 'Unique'],
  ['Athanasios', 'boy', 'Immortal', 'Greek', 'Classic'],
  ['Charalambos', 'boy', 'Joyful light', 'Greek', 'Classic'],
  ['Christos', 'boy', 'Anointed one', 'Greek', 'Classic'],
  ['Christopher', 'boy', 'Bearer of Christ', 'Greek', 'Classic'],
  ['Constantinos', 'boy', 'Steadfast, constant', 'Greek', 'Classic'],
  ['Cosmo', 'boy', 'Order, beauty', 'Greek', 'Unique'],
  ['Demetrios', 'boy', 'Follower of Demeter', 'Greek', 'Classic'],
  ['Dimitris', 'boy', 'Follower of Demeter', 'Greek', 'Modern'],
  ['Dionysios', 'boy', 'Follower of Dionysus', 'Greek', 'Classic'],
  ['Fotis', 'boy', 'Light, radiant', 'Greek', 'Unique'],
  ['Georgios', 'boy', 'Farmer, earthworker', 'Greek', 'Classic'],
  ['Gerasimos', 'boy', 'Honoured, elder', 'Greek', 'Classic'],
  ['Giannis', 'boy', 'God is gracious', 'Greek', 'Modern'],
  ['Gregorios', 'boy', 'Watchful, vigilant', 'Greek', 'Classic'],
  ['Iason', 'boy', 'Healer', 'Greek', 'Unique'],
  ['Isidoros', 'boy', 'Gift of Isis', 'Greek', 'Classic'],
  ['Kosmas', 'boy', 'Order, beauty', 'Greek', 'Classic'],
  ['Kostas', 'boy', 'Steadfast, constant', 'Greek', 'Modern'],
  ['Lazaros', 'boy', 'God has helped', 'Greek', 'Classic'],
  ['Lefteris', 'boy', 'Free, liberator', 'Greek', 'Unique'],
  ['Leon', 'boy', 'Lion', 'Greek', 'Modern'],
  ['Makarios', 'boy', 'Blessed, happy', 'Greek', 'Unique'],
  ['Manolis', 'boy', 'God with us', 'Greek', 'Unique'],
  ['Markos', 'boy', 'Warlike', 'Greek', 'Classic'],
  ['Mihalis', 'boy', 'Who is like God', 'Greek', 'Modern'],
  ['Nektarios', 'boy', 'Of nectar, sweet', 'Greek', 'Unique'],
  ['Nikolaos', 'boy', 'Victory of the people', 'Greek', 'Classic'],
  ['Panagiotis', 'boy', 'All-holy', 'Greek', 'Classic'],
  ['Pavlos', 'boy', 'Small, humble', 'Greek', 'Classic'],
  ['Petros', 'boy', 'Rock, stone', 'Greek', 'Classic'],
  ['Philippos', 'boy', 'Lover of horses', 'Greek', 'Classic'],
  ['Prokopios', 'boy', 'Progress, advance', 'Greek', 'Classic'],
  ['Spyros', 'boy', 'Spirit, breath', 'Greek', 'Classic'],
  ['Stefanos', 'boy', 'Crown, garland', 'Greek', 'Classic'],
  ['Stelios', 'boy', 'Pillar, foundation', 'Greek', 'Modern'],
  ['Takis', 'boy', 'Immortal', 'Greek', 'Unique'],
  ['Thanos', 'boy', 'Immortal', 'Greek', 'Modern'],
  ['Themistoklis', 'boy', 'Renowned for justice', 'Greek', 'Unique'],
  ['Theodoros', 'boy', 'Gift of God', 'Greek', 'Classic'],
  ['Timotheos', 'boy', 'Honouring God', 'Greek', 'Classic'],
  ['Vasilis', 'boy', 'Royal, kingly', 'Greek', 'Classic'],
  ['Xenophon', 'boy', 'Strange voice', 'Greek', 'Unique'],
  ['Yannis', 'boy', 'God is gracious', 'Greek', 'Modern'],
  ['Zacharias', 'boy', 'God remembers', 'Greek', 'Classic'],
  ['Zinon', 'boy', 'Gift of Zeus', 'Greek', 'Unique'],
  ['Alexandra', 'girl', 'Defender of men', 'Greek', 'Classic'],
  ['Anastasia', 'girl', 'Resurrection', 'Greek', 'Classic'],
  ['Angeliki', 'girl', 'Messenger, angel', 'Greek', 'Classic'],
  ['Antigone', 'girl', 'In place of a mother', 'Greek', 'Unique'],
  ['Callista', 'girl', 'Most beautiful', 'Greek', 'Unique'],
  ['Calypso', 'girl', 'She who conceals', 'Greek', 'Unique'],
  ['Christina', 'girl', 'Follower of Christ', 'Greek', 'Classic'],
  ['Daphne', 'girl', 'Laurel tree', 'Greek', 'Modern'],
  ['Dimitra', 'girl', 'Goddess of harvest', 'Greek', 'Classic'],
  ['Electra', 'girl', 'Bright, shining', 'Greek', 'Unique'],
  ['Eudoxia', 'girl', 'Good glory', 'Greek', 'Unique'],
  ['Evi', 'girl', 'Good, well', 'Greek', 'Unique'],
  ['Georgia', 'girl', 'Farmer, earthworker', 'Greek', 'Classic'],
  ['Kalliopi', 'girl', 'Beautiful voice', 'Greek', 'Unique'],
  ['Konstantina', 'girl', 'Steadfast, constant', 'Greek', 'Classic'],
  ['Margarita', 'girl', 'Pearl', 'Greek', 'Classic'],
  ['Melina', 'girl', 'Honey, yellow', 'Greek', 'Unique'],
  ['Nefeli', 'girl', 'Cloud', 'Greek', 'Unique'],
  ['Niki', 'girl', 'Victory', 'Greek', 'Modern'],
  ['Rhea', 'girl', 'Flowing, mother of gods', 'Greek', 'Unique'],
  ['Selene', 'girl', 'Moon', 'Greek', 'Unique'],
  ['Sophia', 'girl', 'Wisdom', 'Greek', 'Modern'],
  ['Stella', 'girl', 'Star', 'Greek', 'Modern'],
  ['Thalia', 'girl', 'Blooming, joyous', 'Greek', 'Unique'],
  ['Theodora', 'girl', 'Gift of God', 'Greek', 'Classic'],
  ['Vasiliki', 'girl', 'Royal, kingly', 'Greek', 'Classic'],
  ['Xanthe', 'girl', 'Golden, yellow', 'Greek', 'Unique'],
  ['Xenia', 'girl', 'Hospitality', 'Greek', 'Unique'],
  ['Zoi', 'girl', 'Life', 'Greek', 'Modern'],
];

export const EXTRA_LATIN = [
  ['Adrian', 'boy', 'From Hadria, dark one', 'Latin', 'Modern'],
  ['Aelius', 'boy', 'Sun', 'Latin', 'Unique'],
  ['Aemilianus', 'boy', 'Rival, eager', 'Latin', 'Unique'],
  ['Albinus', 'boy', 'White, bright', 'Latin', 'Unique'],
  ['Antonius', 'boy', 'Priceless, praiseworthy', 'Latin', 'Classic'],
  ['Atticus', 'boy', 'From Attica', 'Latin', 'Unique'],
  ['Caesar', 'boy', 'Hairy, long-haired', 'Latin', 'Unique'],
  ['Caius', 'boy', 'Rejoice', 'Latin', 'Classic'],
  ['Claudius', 'boy', 'Lame', 'Latin', 'Classic'],
  ['Constantine', 'boy', 'Steadfast, constant', 'Latin', 'Classic'],
  ['Cornelius', 'boy', 'Horn', 'Latin', 'Classic'],
  ['Cyprian', 'boy', 'From Cyprus', 'Latin', 'Unique'],
  ['Fabian', 'boy', 'Bean grower', 'Latin', 'Modern'],
  ['Fabius', 'boy', 'Bean grower', 'Latin', 'Classic'],
  ['Flavius', 'boy', 'Golden, yellow-haired', 'Latin', 'Classic'],
  ['Hadrian', 'boy', 'From Hadria', 'Latin', 'Unique'],
  ['Horace', 'boy', 'Timekeeper', 'Latin', 'Classic'],
  ['Jerome', 'boy', 'Sacred name', 'Latin', 'Classic'],
  ['Leo', 'boy', 'Lion', 'Latin', 'Modern'],
  ['Linus', 'boy', 'Flax, linen', 'Latin', 'Unique'],
  ['Lucian', 'boy', 'Light', 'Latin', 'Unique'],
  ['Marcellus', 'boy', 'Little warrior', 'Latin', 'Classic'],
  ['Nero', 'boy', 'Strong, stern', 'Latin', 'Unique'],
  ['Octavian', 'boy', 'Eighth', 'Latin', 'Classic'],
  ['Ovid', 'boy', 'Shepherd', 'Latin', 'Unique'],
  ['Paul', 'boy', 'Small, humble', 'Latin', 'Classic'],
  ['Quintus', 'boy', 'Fifth', 'Latin', 'Classic'],
  ['Rufus', 'boy', 'Red-haired', 'Latin', 'Unique'],
  ['Severus', 'boy', 'Stern, severe', 'Latin', 'Unique'],
  ['Sylvester', 'boy', 'Of the forest', 'Latin', 'Classic'],
  ['Terence', 'boy', 'Tender, gentle', 'Latin', 'Classic'],
  ['Tiberius', 'boy', 'Of the Tiber', 'Latin', 'Unique'],
  ['Valens', 'boy', 'Strong, healthy', 'Latin', 'Unique'],
  ['Valentinus', 'boy', 'Strong, healthy', 'Latin', 'Classic'],
  ['Vincent', 'boy', 'Conquering', 'Latin', 'Classic'],
  ['Virgil', 'boy', 'Staff bearer', 'Latin', 'Classic'],
  ['Adriana', 'girl', 'From Hadria, dark one', 'Latin', 'Modern'],
  ['Aemilia', 'girl', 'Rival, eager', 'Latin', 'Classic'],
  ['Albina', 'girl', 'White, bright', 'Latin', 'Unique'],
  ['Antonia', 'girl', 'Priceless, praiseworthy', 'Latin', 'Classic'],
  ['Beatrix', 'girl', 'She who brings happiness', 'Latin', 'Modern'],
  ['Caecilia', 'girl', 'Blind, dim-sighted', 'Latin', 'Unique'],
  ['Cecilia', 'girl', 'Blind, musical', 'Latin', 'Classic'],
  ['Celestine', 'girl', 'Heavenly', 'Latin', 'Unique'],
  ['Clementina', 'girl', 'Merciful, gentle', 'Latin', 'Unique'],
  ['Cornelia', 'girl', 'Horn', 'Latin', 'Classic'],
  ['Domitilla', 'girl', 'Tamed', 'Latin', 'Unique'],
  ['Drusilla', 'girl', 'Strong', 'Latin', 'Unique'],
  ['Flavia', 'girl', 'Golden, blonde', 'Latin', 'Classic'],
  ['Justina', 'girl', 'Just, fair', 'Latin', 'Classic'],
  ['Laetitia', 'girl', 'Joy, happiness', 'Latin', 'Unique'],
  ['Luciana', 'girl', 'Light', 'Latin', 'Unique'],
  ['Marcella', 'girl', 'Little warrior', 'Latin', 'Classic'],
  ['Marcia', 'girl', 'Warlike', 'Latin', 'Classic'],
  ['Maxima', 'girl', 'Greatest', 'Latin', 'Unique'],
  ['Paulina', 'girl', 'Small, humble', 'Latin', 'Classic'],
  ['Priscilla', 'girl', 'Ancient', 'Latin', 'Classic'],
  ['Sylvia', 'girl', 'Of the forest', 'Latin', 'Classic'],
  ['Tullia', 'girl', 'Peaceful', 'Latin', 'Unique'],
  ['Ursula', 'girl', 'Little she-bear', 'Latin', 'Classic'],
  ['Valeria', 'girl', 'Strong, healthy', 'Latin', 'Classic'],
  ['Vibia', 'girl', 'Alive, lively', 'Latin', 'Unique'],
];

export const EXTRA_HEBREW = [
  ['Aaron', 'boy', 'High mountain, exalted', 'Hebrew', 'Classic'],
  ['Abner', 'boy', 'Father of light', 'Hebrew', 'Unique'],
  ['Abraham', 'boy', 'Father of many', 'Hebrew', 'Classic'],
  ['Amos', 'boy', 'Burden, carried by God', 'Hebrew', 'Classic'],
  ['Avi', 'boy', 'My father', 'Hebrew', 'Unique'],
  ['Azariah', 'boy', 'God has helped', 'Hebrew', 'Unique'],
  ['Binyamin', 'boy', 'Son of the right hand', 'Hebrew', 'Classic'],
  ['Elijah', 'boy', 'My God is Yahweh', 'Hebrew', 'Modern'],
  ['Elisha', 'boy', 'God is salvation', 'Hebrew', 'Unique'],
  ['Emmanuel', 'boy', 'God with us', 'Hebrew', 'Classic'],
  ['Ephraim', 'boy', 'Fruitful', 'Hebrew', 'Unique'],
  ['Gershom', 'boy', 'Exile, stranger', 'Hebrew', 'Unique'],
  ['Gil', 'boy', 'Joy, happiness', 'Hebrew', 'Unique'],
  ['Hezekiah', 'boy', 'God gives strength', 'Hebrew', 'Unique'],
  ['Hillel', 'boy', 'Praise', 'Hebrew', 'Unique'],
  ['Hosea', 'boy', 'Salvation', 'Hebrew', 'Unique'],
  ['Isaiah', 'boy', 'God is salvation', 'Hebrew', 'Modern'],
  ['Israel', 'boy', 'He who struggles with God', 'Hebrew', 'Unique'],
  ['Jabez', 'boy', 'Sorrow, borne in pain', 'Hebrew', 'Unique'],
  ['Jethro', 'boy', 'Excellence, abundance', 'Hebrew', 'Unique'],
  ['Jorah', 'boy', 'Early rain', 'Hebrew', 'Unique'],
  ['Josiah', 'boy', 'God supports', 'Hebrew', 'Unique'],
  ['Malachi', 'boy', 'My messenger', 'Hebrew', 'Modern'],
  ['Manasseh', 'boy', 'Forgetfulness', 'Hebrew', 'Unique'],
  ['Micah', 'boy', 'Who is like God', 'Hebrew', 'Modern'],
  ['Mordechai', 'boy', 'Warrior, little man', 'Hebrew', 'Classic'],
  ['Nahum', 'boy', 'Comforter', 'Hebrew', 'Unique'],
  ['Nehemiah', 'boy', 'God comforts', 'Hebrew', 'Unique'],
  ['Obadiah', 'boy', 'Servant of God', 'Hebrew', 'Unique'],
  ['Oren', 'boy', 'Pine tree', 'Hebrew', 'Unique'],
  ['Raphael', 'boy', 'God has healed', 'Hebrew', 'Modern'],
  ['Samson', 'boy', 'Sun, of the sun', 'Hebrew', 'Classic'],
  ['Shem', 'boy', 'Name, renown', 'Hebrew', 'Unique'],
  ['Simeon', 'boy', 'Heard', 'Hebrew', 'Classic'],
  ['Simon', 'boy', 'Heard, hearkening', 'Hebrew', 'Classic'],
  ['Uriel', 'boy', 'God is my light', 'Hebrew', 'Unique'],
  ['Zachariah', 'boy', 'God remembers', 'Hebrew', 'Classic'],
  ['Zebulon', 'boy', 'Dwelling, honour', 'Hebrew', 'Unique'],
  ['Zechariah', 'boy', 'God remembers', 'Hebrew', 'Classic'],
  ['Zev', 'boy', 'Wolf', 'Hebrew', 'Unique'],
  ['Ada', 'girl', 'Adornment, noble', 'Hebrew', 'Unique'],
  ['Ayelet', 'girl', 'Gazelle', 'Hebrew', 'Unique'],
  ['Batya', 'girl', 'Daughter of God', 'Hebrew', 'Unique'],
  ['Chava', 'girl', 'Life', 'Hebrew', 'Unique'],
  ['Chaya', 'girl', 'Life', 'Hebrew', 'Unique'],
  ['Dalia', 'girl', 'Branch, slender', 'Hebrew', 'Unique'],
  ['Dinah', 'girl', 'Judged, vindicated', 'Hebrew', 'Unique'],
  ['Eliza', 'girl', 'God is my oath', 'Hebrew', 'Unique'],
  ['Gila', 'girl', 'Joy', 'Hebrew', 'Unique'],
  ['Hadar', 'girl', 'Splendour, beauty', 'Hebrew', 'Unique'],
  ['Hephzibah', 'girl', 'My delight is in her', 'Hebrew', 'Unique'],
  ['Ilana', 'girl', 'Tree', 'Hebrew', 'Unique'],
  ['Jordana', 'girl', 'Flowing down, earth', 'Hebrew', 'Unique'],
  ['Judith', 'girl', 'Praised', 'Hebrew', 'Classic'],
  ['Kezia', 'girl', 'Cassia, cinnamon', 'Hebrew', 'Unique'],
  ['Libby', 'girl', 'God is my oath', 'Hebrew', 'Modern'],
  ['Michal', 'girl', 'Who is like God', 'Hebrew', 'Unique'],
  ['Moriah', 'girl', 'Chosen by God', 'Hebrew', 'Unique'],
  ['Nava', 'girl', 'Beautiful, pleasant', 'Hebrew', 'Unique'],
  ['Noa', 'girl', 'Motion, movement', 'Hebrew', 'Modern'],
  ['Odelia', 'girl', 'I will praise God', 'Hebrew', 'Unique'],
  ['Ori', 'girl', 'My light', 'Hebrew', 'Unique'],
  ['Rina', 'girl', 'Joy, song', 'Hebrew', 'Unique'],
  ['Rivka', 'girl', 'To bind, captivating', 'Hebrew', 'Classic'],
  ['Shalom', 'girl', 'Peace', 'Hebrew', 'Unique'],
  ['Shifra', 'girl', 'Beautiful, fair', 'Hebrew', 'Unique'],
  ['Talia', 'girl', 'Dew of heaven', 'Hebrew', 'Modern'],
  ['Tova', 'girl', 'Good', 'Hebrew', 'Unique'],
  ['Yael', 'girl', 'Mountain goat', 'Hebrew', 'Unique'],
  ['Zahava', 'girl', 'Golden', 'Hebrew', 'Unique'],
];
